package test.po;



/**
 * Test generated by MyEclipse - Hibernate Tools
 */

public class Test  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -3165976462992313885L;
	private String id;
     private String name;


    // Constructors

    /** default constructor */
    public Test() {
    }

    
    /** full constructor */
    public Test(String id, String name) {
        this.id = id;
        this.name = name;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
   








}