package airticket.po;


/**
 * DromecodeId generated by MyEclipse - Hibernate Tools
 */

public class DromeCodeId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -671789197650063440L;
	private String area;
     private String airDrome;
     private String dromeCode;


    // Constructors

    /** default constructor */
    public DromeCodeId() {
    }

    
    /** full constructor */
    public DromeCodeId(String area, String airdrome, String dromecode) {
        this.area = area;
        this.airDrome = airdrome;
        this.dromeCode = dromecode;
    }

   
    // Property accessors

    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

    public String getAirDrome() {
        return this.airDrome;
    }
    
    public void setAirDrome(String airDrome) {
        this.airDrome = airDrome;
    }

    public String getDromeCode() {
        return this.dromeCode;
    }
    
    public void setDromeCode(String dromeCode) {
        this.dromeCode = dromeCode;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DromeCodeId) ) return false;
		 DromeCodeId castOther = ( DromeCodeId ) other; 
         
		 return ( (this.getArea()==castOther.getArea()) || ( this.getArea()!=null && castOther.getArea()!=null && this.getArea().equals(castOther.getArea()) ) )
 && ( (this.getAirDrome()==castOther.getAirDrome()) || ( this.getAirDrome()!=null && castOther.getAirDrome()!=null && this.getAirDrome().equals(castOther.getAirDrome()) ) )
 && ( (this.getDromeCode()==castOther.getDromeCode()) || ( this.getDromeCode()!=null && castOther.getDromeCode()!=null && this.getDromeCode().equals(castOther.getDromeCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getArea() == null ? 0 : this.getArea().hashCode() );
         result = 37 * result + ( getAirDrome() == null ? 0 : this.getAirDrome().hashCode() );
         result = 37 * result + ( getDromeCode() == null ? 0 : this.getDromeCode().hashCode() );
         return result;
   }   





}
