package airticket.po;



/**
 * Dromecode generated by MyEclipse - Hibernate Tools
 */

public class DromeCode  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -5491071045866015965L;
	private DromeCodeId id;


    // Constructors

    /** default constructor */
    public DromeCode() {
    }

    
    /** full constructor */
    public DromeCode(DromeCodeId id) {
        this.id = id;
    }

   
    // Property accessors

    public DromeCodeId getId() {
        return this.id;
    }
    
    public void setId(DromeCodeId id) {
        this.id = id;
    }
   








}