package airticket.po;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Userinfo generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class Userinfo  implements java.io.Serializable {


    // Fields    

     private Long userid;
     private String username;
     private String pasword;
     private String phone;
     private String tel;
     private String fax;
     private String email;
     private String truename;
     private Date birthday;
     private String credentialsid;
     private String credentialstype;
     private String sex;
     private String country;
     private String province;
     private String address;
     private String postcode;
     private Date registerdate;
     private Date lasttime;
     private String status;
     private String usable;
     private Long airscore;
     private Long aircost;
     private Long foreignairscore;
     private Long foreignaircosts;
     private Long hotelscore;
     private Long hotelcost;
     private Long travelscore;
     private Long travelcost;
     private Set userscores = new HashSet(0);
     private Set airorders = new HashSet(0);


    // Constructors

    /** default constructor */
    public Userinfo() {
    }

	/** minimal constructor */
    public Userinfo(Long userid, String username) {
        this.userid = userid;
        this.username = username;
    }
    
    /** full constructor */
    public Userinfo(Long userid, String username, String pasword, String phone, String tel, String fax, String email, String truename, Date birthday, String credentialsid, String credentialstype, String sex, String country, String province, String address, String postcode, Date registerdate, Date lasttime, String status, String usable, Long airscore, Long aircost, Long foreignairscore, Long foreignaircosts, Long hotelscore, Long hotelcost, Long travelscore, Long travelcost, Set userscores, Set airorders) {
        this.userid = userid;
        this.username = username;
        this.pasword = pasword;
        this.phone = phone;
        this.tel = tel;
        this.fax = fax;
        this.email = email;
        this.truename = truename;
        this.birthday = birthday;
        this.credentialsid = credentialsid;
        this.credentialstype = credentialstype;
        this.sex = sex;
        this.country = country;
        this.province = province;
        this.address = address;
        this.postcode = postcode;
        this.registerdate = registerdate;
        this.lasttime = lasttime;
        this.status = status;
        this.usable = usable;
        this.airscore = airscore;
        this.aircost = aircost;
        this.foreignairscore = foreignairscore;
        this.foreignaircosts = foreignaircosts;
        this.hotelscore = hotelscore;
        this.hotelcost = hotelcost;
        this.travelscore = travelscore;
        this.travelcost = travelcost;
        this.userscores = userscores;
        this.airorders = airorders;
    }

   
    // Property accessors

    public Long getUserid() {
        return this.userid;
    }
    
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPasword() {
        return this.pasword;
    }
    
    public void setPasword(String pasword) {
        this.pasword = pasword;
    }

    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getTruename() {
        return this.truename;
    }
    
    public void setTruename(String truename) {
        this.truename = truename;
    }

    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getCredentialsid() {
        return this.credentialsid;
    }
    
    public void setCredentialsid(String credentialsid) {
        this.credentialsid = credentialsid;
    }

    public String getCredentialstype() {
        return this.credentialstype;
    }
    
    public void setCredentialstype(String credentialstype) {
        this.credentialstype = credentialstype;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public Date getRegisterdate() {
        return this.registerdate;
    }
    
    public void setRegisterdate(Date registerdate) {
        this.registerdate = registerdate;
    }

    public Date getLasttime() {
        return this.lasttime;
    }
    
    public void setLasttime(Date lasttime) {
        this.lasttime = lasttime;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getUsable() {
        return this.usable;
    }
    
    public void setUsable(String usable) {
        this.usable = usable;
    }

    public Long getAirscore() {
        return this.airscore;
    }
    
    public void setAirscore(Long airscore) {
        this.airscore = airscore;
    }

    public Long getAircost() {
        return this.aircost;
    }
    
    public void setAircost(Long aircost) {
        this.aircost = aircost;
    }

    public Long getForeignairscore() {
        return this.foreignairscore;
    }
    
    public void setForeignairscore(Long foreignairscore) {
        this.foreignairscore = foreignairscore;
    }

    public Long getForeignaircosts() {
        return this.foreignaircosts;
    }
    
    public void setForeignaircosts(Long foreignaircosts) {
        this.foreignaircosts = foreignaircosts;
    }

    public Long getHotelscore() {
        return this.hotelscore;
    }
    
    public void setHotelscore(Long hotelscore) {
        this.hotelscore = hotelscore;
    }

    public Long getHotelcost() {
        return this.hotelcost;
    }
    
    public void setHotelcost(Long hotelcost) {
        this.hotelcost = hotelcost;
    }

    public Long getTravelscore() {
        return this.travelscore;
    }
    
    public void setTravelscore(Long travelscore) {
        this.travelscore = travelscore;
    }

    public Long getTravelcost() {
        return this.travelcost;
    }
    
    public void setTravelcost(Long travelcost) {
        this.travelcost = travelcost;
    }

    public Set getUserscores() {
        return this.userscores;
    }
    
    public void setUserscores(Set userscores) {
        this.userscores = userscores;
    }

    public Set getAirorders() {
        return this.airorders;
    }
    
    public void setAirorders(Set airorders) {
        this.airorders = airorders;
    }
   
}