package airticket.po;


import java.util.Date;


/**
 * Userscore generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class Userscore  implements java.io.Serializable {


    // Fields    

     private String scoreid;
     private Userinfo userinfo;
     private String username;
     private Long obtainscore;
     private Long costscore;
     private Date updscotime;
     private String orderid;
     private String eventid;


    // Constructors

    /** default constructor */
    public Userscore() {
    }

	/** minimal constructor */
    public Userscore(String scoreid, Userinfo userinfo, String username, Date updscotime) {
        this.scoreid = scoreid;
        this.userinfo = userinfo;
        this.username = username;
        this.updscotime = updscotime;
    }
    
    /** full constructor */
    public Userscore(String scoreid, Userinfo userinfo, String username, Long obtainscore, Long costscore, Date updscotime, String orderid, String eventid) {
        this.scoreid = scoreid;
        this.userinfo = userinfo;
        this.username = username;
        this.obtainscore = obtainscore;
        this.costscore = costscore;
        this.updscotime = updscotime;
        this.orderid = orderid;
        this.eventid = eventid;
    }

   
    // Property accessors

    public String getScoreid() {
        return this.scoreid;
    }
    
    public void setScoreid(String scoreid) {
        this.scoreid = scoreid;
    }

    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public Long getObtainscore() {
        return this.obtainscore;
    }
    
    public void setObtainscore(Long obtainscore) {
        this.obtainscore = obtainscore;
    }

    public Long getCostscore() {
        return this.costscore;
    }
    
    public void setCostscore(Long costscore) {
        this.costscore = costscore;
    }

    public Date getUpdscotime() {
        return this.updscotime;
    }
    
    public void setUpdscotime(Date updscotime) {
        this.updscotime = updscotime;
    }

    public String getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    public String getEventid() {
        return this.eventid;
    }
    
    public void setEventid(String eventid) {
        this.eventid = eventid;
    }
   








}