package airticket.po;


import java.util.Date;


/**
 * Airorder generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class Airorder  implements java.io.Serializable {


    // Fields    

     private AirorderId id;
     private Userinfo userinfo;
     private String passengertype;
     private String credentialstype;
     private String credentialsid;
     private String pnr;
     private String airtype;
     private String scope;
     private String airpalnetype1;
     private String airno;
     private String sert1;
     private String fromcity1;
     private String tocity1;
     private Date airtime1;
     private Date gairtime1;
     private Float fare1;
     private Float myc1;
     private Float airportbuild1;
     private String stop1;
     private String food1;
     private String rmk1;
     private String airpalnetype2;
     private String airno2;
     private String sert2;
     private String fromcity2;
     private String tocity2;
     private Date airtime2;
     private Date gairtime2;
     private Float fare2;
     private Float myc2;
     private Float airportbuild2;
     private String stop2;
     private String food2;
     private String rmk2;
     private Long scorepay;
     private Long promotionpay;
     private String tel;
     private String note;
     private String static_;
     private Date dateortime;
     private Long discount2;
     private Long discount1;
     private Float kfare;
     private String promulgator;
     private String paymentform;
     private Date paydate;
     private String payorderid;
     private String et;
     private String tkno;
     private String isrr;
     private String getaddress;
     private String sendaddress;
     private String contactperson;
     private String orderer;


    // Constructors

    /** default constructor */
    public Airorder() {
    }

	/** minimal constructor */
    public Airorder(AirorderId id, Userinfo userinfo) {
        this.id = id;
        this.userinfo = userinfo;
    }
    
    /** full constructor */
    public Airorder(AirorderId id, Userinfo userinfo, String passengertype, String credentialstype, String credentialsid, String pnr, String airtype, String scope, String airpalnetype1, String airno, String sert1, String fromcity1, String tocity1, Date airtime1, Date gairtime1, Float fare1, Float myc1, Float airportbuild1, String stop1, String food1, String rmk1, String airpalnetype2, String airno2, String sert2, String fromcity2, String tocity2, Date airtime2, Date gairtime2, Float fare2, Float myc2, Float airportbuild2, String stop2, String food2, String rmk2, Long scorepay, Long promotionpay, String tel, String note, String static_, Date dateortime, Long discount2, Long discount1, Float kfare, String promulgator, String paymentform, Date paydate, String payorderid, String et, String tkno, String isrr, String getaddress, String sendaddress, String contactperson, String orderer) {
        this.id = id;
        this.userinfo = userinfo;
        this.passengertype = passengertype;
        this.credentialstype = credentialstype;
        this.credentialsid = credentialsid;
        this.pnr = pnr;
        this.airtype = airtype;
        this.scope = scope;
        this.airpalnetype1 = airpalnetype1;
        this.airno = airno;
        this.sert1 = sert1;
        this.fromcity1 = fromcity1;
        this.tocity1 = tocity1;
        this.airtime1 = airtime1;
        this.gairtime1 = gairtime1;
        this.fare1 = fare1;
        this.myc1 = myc1;
        this.airportbuild1 = airportbuild1;
        this.stop1 = stop1;
        this.food1 = food1;
        this.rmk1 = rmk1;
        this.airpalnetype2 = airpalnetype2;
        this.airno2 = airno2;
        this.sert2 = sert2;
        this.fromcity2 = fromcity2;
        this.tocity2 = tocity2;
        this.airtime2 = airtime2;
        this.gairtime2 = gairtime2;
        this.fare2 = fare2;
        this.myc2 = myc2;
        this.airportbuild2 = airportbuild2;
        this.stop2 = stop2;
        this.food2 = food2;
        this.rmk2 = rmk2;
        this.scorepay = scorepay;
        this.promotionpay = promotionpay;
        this.tel = tel;
        this.note = note;
        this.static_ = static_;
        this.dateortime = dateortime;
        this.discount2 = discount2;
        this.discount1 = discount1;
        this.kfare = kfare;
        this.promulgator = promulgator;
        this.paymentform = paymentform;
        this.paydate = paydate;
        this.payorderid = payorderid;
        this.et = et;
        this.tkno = tkno;
        this.isrr = isrr;
        this.getaddress = getaddress;
        this.sendaddress = sendaddress;
        this.contactperson = contactperson;
        this.orderer = orderer;
    }

   
    // Property accessors

    public AirorderId getId() {
        return this.id;
    }
    
    public void setId(AirorderId id) {
        this.id = id;
    }

    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }

    public String getPassengertype() {
        return this.passengertype;
    }
    
    public void setPassengertype(String passengertype) {
        this.passengertype = passengertype;
    }

    public String getCredentialstype() {
        return this.credentialstype;
    }
    
    public void setCredentialstype(String credentialstype) {
        this.credentialstype = credentialstype;
    }

    public String getCredentialsid() {
        return this.credentialsid;
    }
    
    public void setCredentialsid(String credentialsid) {
        this.credentialsid = credentialsid;
    }

    public String getPnr() {
        return this.pnr;
    }
    
    public void setPnr(String pnr) {
        this.pnr = pnr;
    }

    public String getAirtype() {
        return this.airtype;
    }
    
    public void setAirtype(String airtype) {
        this.airtype = airtype;
    }

    public String getScope() {
        return this.scope;
    }
    
    public void setScope(String scope) {
        this.scope = scope;
    }

    public String getAirpalnetype1() {
        return this.airpalnetype1;
    }
    
    public void setAirpalnetype1(String airpalnetype1) {
        this.airpalnetype1 = airpalnetype1;
    }

    public String getAirno() {
        return this.airno;
    }
    
    public void setAirno(String airno) {
        this.airno = airno;
    }

    public String getSert1() {
        return this.sert1;
    }
    
    public void setSert1(String sert1) {
        this.sert1 = sert1;
    }

    public String getFromcity1() {
        return this.fromcity1;
    }
    
    public void setFromcity1(String fromcity1) {
        this.fromcity1 = fromcity1;
    }

    public String getTocity1() {
        return this.tocity1;
    }
    
    public void setTocity1(String tocity1) {
        this.tocity1 = tocity1;
    }

    public Date getAirtime1() {
        return this.airtime1;
    }
    
    public void setAirtime1(Date airtime1) {
        this.airtime1 = airtime1;
    }

    public Date getGairtime1() {
        return this.gairtime1;
    }
    
    public void setGairtime1(Date gairtime1) {
        this.gairtime1 = gairtime1;
    }

    public Float getFare1() {
        return this.fare1;
    }
    
    public void setFare1(Float fare1) {
        this.fare1 = fare1;
    }

    public Float getMyc1() {
        return this.myc1;
    }
    
    public void setMyc1(Float myc1) {
        this.myc1 = myc1;
    }

    public Float getAirportbuild1() {
        return this.airportbuild1;
    }
    
    public void setAirportbuild1(Float airportbuild1) {
        this.airportbuild1 = airportbuild1;
    }

    public String getStop1() {
        return this.stop1;
    }
    
    public void setStop1(String stop1) {
        this.stop1 = stop1;
    }

    public String getFood1() {
        return this.food1;
    }
    
    public void setFood1(String food1) {
        this.food1 = food1;
    }

    public String getRmk1() {
        return this.rmk1;
    }
    
    public void setRmk1(String rmk1) {
        this.rmk1 = rmk1;
    }

    public String getAirpalnetype2() {
        return this.airpalnetype2;
    }
    
    public void setAirpalnetype2(String airpalnetype2) {
        this.airpalnetype2 = airpalnetype2;
    }

    public String getAirno2() {
        return this.airno2;
    }
    
    public void setAirno2(String airno2) {
        this.airno2 = airno2;
    }

    public String getSert2() {
        return this.sert2;
    }
    
    public void setSert2(String sert2) {
        this.sert2 = sert2;
    }

    public String getFromcity2() {
        return this.fromcity2;
    }
    
    public void setFromcity2(String fromcity2) {
        this.fromcity2 = fromcity2;
    }

    public String getTocity2() {
        return this.tocity2;
    }
    
    public void setTocity2(String tocity2) {
        this.tocity2 = tocity2;
    }

    public Date getAirtime2() {
        return this.airtime2;
    }
    
    public void setAirtime2(Date airtime2) {
        this.airtime2 = airtime2;
    }

    public Date getGairtime2() {
        return this.gairtime2;
    }
    
    public void setGairtime2(Date gairtime2) {
        this.gairtime2 = gairtime2;
    }

    public Float getFare2() {
        return this.fare2;
    }
    
    public void setFare2(Float fare2) {
        this.fare2 = fare2;
    }

    public Float getMyc2() {
        return this.myc2;
    }
    
    public void setMyc2(Float myc2) {
        this.myc2 = myc2;
    }

    public Float getAirportbuild2() {
        return this.airportbuild2;
    }
    
    public void setAirportbuild2(Float airportbuild2) {
        this.airportbuild2 = airportbuild2;
    }

    public String getStop2() {
        return this.stop2;
    }
    
    public void setStop2(String stop2) {
        this.stop2 = stop2;
    }

    public String getFood2() {
        return this.food2;
    }
    
    public void setFood2(String food2) {
        this.food2 = food2;
    }

    public String getRmk2() {
        return this.rmk2;
    }
    
    public void setRmk2(String rmk2) {
        this.rmk2 = rmk2;
    }

    public Long getScorepay() {
        return this.scorepay;
    }
    
    public void setScorepay(Long scorepay) {
        this.scorepay = scorepay;
    }

    public Long getPromotionpay() {
        return this.promotionpay;
    }
    
    public void setPromotionpay(Long promotionpay) {
        this.promotionpay = promotionpay;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    public String getStatic_() {
        return this.static_;
    }
    
    public void setStatic_(String static_) {
        this.static_ = static_;
    }

    public Date getDateortime() {
        return this.dateortime;
    }
    
    public void setDateortime(Date dateortime) {
        this.dateortime = dateortime;
    }

    public Long getDiscount2() {
        return this.discount2;
    }
    
    public void setDiscount2(Long discount2) {
        this.discount2 = discount2;
    }

    public Long getDiscount1() {
        return this.discount1;
    }
    
    public void setDiscount1(Long discount1) {
        this.discount1 = discount1;
    }

    public Float getKfare() {
        return this.kfare;
    }
    
    public void setKfare(Float kfare) {
        this.kfare = kfare;
    }

    public String getPromulgator() {
        return this.promulgator;
    }
    
    public void setPromulgator(String promulgator) {
        this.promulgator = promulgator;
    }

    public String getPaymentform() {
        return this.paymentform;
    }
    
    public void setPaymentform(String paymentform) {
        this.paymentform = paymentform;
    }

    public Date getPaydate() {
        return this.paydate;
    }
    
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    public String getPayorderid() {
        return this.payorderid;
    }
    
    public void setPayorderid(String payorderid) {
        this.payorderid = payorderid;
    }

    public String getEt() {
        return this.et;
    }
    
    public void setEt(String et) {
        this.et = et;
    }

    public String getTkno() {
        return this.tkno;
    }
    
    public void setTkno(String tkno) {
        this.tkno = tkno;
    }

    public String getIsrr() {
        return this.isrr;
    }
    
    public void setIsrr(String isrr) {
        this.isrr = isrr;
    }

    public String getGetaddress() {
        return this.getaddress;
    }
    
    public void setGetaddress(String getaddress) {
        this.getaddress = getaddress;
    }

    public String getSendaddress() {
        return this.sendaddress;
    }
    
    public void setSendaddress(String sendaddress) {
        this.sendaddress = sendaddress;
    }

    public String getContactperson() {
        return this.contactperson;
    }
    
    public void setContactperson(String contactperson) {
        this.contactperson = contactperson;
    }

    public String getOrderer() {
        return this.orderer;
    }
    
    public void setOrderer(String orderer) {
        this.orderer = orderer;
    }
   








}