package airticket.po;




/**
 * AirorderId generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class AirorderId  implements java.io.Serializable {


    // Fields    

     private String orderid;
     private String name;


    // Constructors

    /** default constructor */
    public AirorderId() {
    }

    
    /** full constructor */
    public AirorderId(String orderid, String name) {
        this.orderid = orderid;
        this.name = name;
    }

   
    // Property accessors

    public String getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AirorderId) ) return false;
		 AirorderId castOther = ( AirorderId ) other; 
         
		 return ( (this.getOrderid()==castOther.getOrderid()) || ( this.getOrderid()!=null && castOther.getOrderid()!=null && this.getOrderid().equals(castOther.getOrderid()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOrderid() == null ? 0 : this.getOrderid().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         return result;
   }   





}